### ISSUE TITLE
Add discussion on completeness

### ISSUE THREAD

**Issue by krtab** [OCamlPro/verification_for_dummies#1]
It could be interesting to add a bit on completeness here:

https://github.com/OCamlPro/verification_for_dummies/blob/c17f56cba61c959371a63ea694feb3c328dfe45f/src/preface/readme.md?plain=1#L221-L223

Upon first reading, I had a biologist like mentality of "if there is unsoundness (false-negative) at least there must be no false positive", but after giving it a bit more thought, I realized that in verification, one rarely has completeness guarantees (depending I guess on how you define it). Typically, the borrow checker rejects things that would work in practice (however, it does not reject anything matching the spec).
It could be interesting to add some discussion on this topic around this part of the book.

**Comment by AdrienChampion** [comment]
*Soundness* (and *completeness*) have different/opposite meanings depending on the context. So do *false negative/positive* in fact. It's a nightmare to discuss publicly as people will have opposite definitions for these terms depending on their background. That's why these concepts are discussed very briefly, in passing.

> What follows is what **I** am used to. Don't **@me**.

**Usually**, a verification process is *sound* if whenever it manages to construct a proof for some proposition `P`, then `P` is actually *valid* (in the model-theoretic sense). So a technique is *unsound* if it creates **false positives**, *i.e.* it proves `P` but `P` is not actually valid (does not hold).

> The verification process of "does this unit test work on this code base" for instance is unsound as far as verifying the whole code base goes. If the test runs as expected, we cannot conclude much regarding the whole code base. More generally, "does this code base pass all its tests" is always unsound in this sense. It is quite valuable for bug-finding though.

Conversely, a verification process is *complete* if whenever `P` is valid, then the process will find a proof of `P`. Hence a technique is incomplete if there are valid propositions it cannot prove, potentially even producing **false negatives**. A false negative here is either the process answering *"no proof found for `P`"* or a **tentative** counterexample (*"maybe this counterexample falsifies the proposition"*).

> Induction over transition systems is incomplete as invariants of a system are not necessarily inductive. If the step/induction check for `P` fails, then all we can say is that `P` is not inductive and give the step counterexample but that's it, `P` might still be an invariant. That's why you typically also run Bounded Model-Checking to try to find an actual counterexample if one exists and is reachable in reasonable time.

As you pointed out, we rarely have completeness in verification since we are routinely in non-decidable fragments. Even when we are in a decidable fragment, we're *at best* NP-complete (often `k`-exp TIME) so completeness is not really practical. You get *"timeout"* instead of *"I don't know"* but it's pretty much the same from the outside.

**Comment by AdrienChampion** [comment]
So yeah, really don't want to get into such a discussion as this series is mostly for verification-agnostic people and I feel this would detract more than it would clarify. A case can be made for adding this kind of discussion towards the end of the series though.
The last bit, *strengthening*, actually deals with non-decidable/very expensive fragments so arguably we could discuss it there I guess.

**Comment by krtab** [comment]
Ok, perfectly understandable why you don't want to get into more details.
Thanks for the *very* detailed answer!
